FROM node:13.3.0-alpine3.10

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
ADD . /usr/src/app

RUN npm install -g -s --no-progress yarn && \
    yarn && \
    yarn run build && \
    yarn cache clean

COPY . /usr/src/app

EXPOSE 3000
CMD ["npm", "start"]